php artisan krlove:generate:model User
php artisan krlove:generate:model Category
php artisan krlove:generate:model Content
php artisan krlove:generate:model Level
php artisan krlove:generate:model Staff
php artisan krlove:generate:model Association
php artisan krlove:generate:model Document
php artisan krlove:generate:model Citizen
php artisan krlove:generate:model File
